# Right leg

r_hip_yaw_controller: #Done
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: r_hip_yaw_joint
    joint_speed: 1.17
    motor:
        id: 1
        init: 512
        min: 0
        max: 1023

r_hip_roll_controller: #Done
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: r_hip_roll_joint
    joint_speed: 1.0
    motor:
        id: 2
        init: 512
        min: 0
        max: 1023

r_hip_pitch_controller: #Done
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: r_hip_pitch_joint
    joint_speed: 1.0
    motor:
        id: 3
        init: 512
        min: 0
        max: 1023

r_knee_pitch_controller: #Done
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: r_knee_pitch_joint
    joint_speed: 1.0
    torque_enable: false
    motor:
        id: 4
        init: 512
        min: 0
        max: 1023

r_ankle_pitch_controller: #Done
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: r_ankle_pitch_joint
    joint_speed: 5.0
    torque_enable: false
    motor:
        id: 5
        init: 512
        min: 0
        max: 1023

r_ankle_roll_controller: #Done
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: r_ankle_roll_joint
    joint_speed: 5.0
    motor:
        id: 6
        init: 512
        min: 0
        max: 1023


# Left leg

l_hip_yaw_controller: #Motor not working?
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: l_hip_yaw_joint
    joint_speed: 1.0
    motor:
        id: 7
        init: 2048
        min: 0
        max: 4095

#        init: 305
#        min: 145
#        max: 549

l_hip_roll_controller: #Done
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: l_hip_roll_joint
    joint_speed: 1.0
    motor:
        id: 8
        init: 512
        min: 0
        max: 1023

l_hip_pitch_controller: #Done
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: l_hip_pitch_joint
    joint_speed: 1.0
    motor:
        id: 9
        init: 512
        min: 0
        max: 1023

l_knee_pitch_controller: #Done
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: l_knee_pitch_joint
    joint_speed: 1.0
    motor:
        id: 10
        init: 512
        min: 0
        max: 1023

l_ankle_pitch_controller: #Done
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: l_ankle_pitch_joint
    joint_speed: 5.0
    motor:
        id: 11
        init: 512
        min: 0
        max: 1023

l_ankle_roll_controller: #Done
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: l_ankle_roll_joint
    joint_speed: 5.0
    motor:
        id: 12
        init: 512
        min: 0
        max: 1023
